### ISSUE TITLE
KeyboardAwareScrollView do not work any more on iOS 26

### ISSUE THREAD

**Issue by asadarshad142** [kirillzyusko/react-native-keyboard-controller#1044]
**Describe the bug**
KeyboardAwareScrollView  dont work any more on iOS 26, can someone please confirm it? it dont scroll when keyboard opens

**Code snippet**
```
<KeyboardAwareScrollView keyboardShouldPersistTaps="handled" bottomOffset={62} contentContainerStyle={styles.scrollContainer} style={{ flex: 1, marginBottom: bottom, backgroundColor: Colors.light.background }}>
        <View style={styles.profileSection}>
          {isUploadingImage ? (
            <View style={styles.loadingContainer}>
              <ActivityIndicator size="small" color="#007AFF" />
              <ThemedText style={styles.loadingText}>Uploading...</ThemedText>
            </View>
          ) : profile?.profilePicture ? (
            <View style={styles.imageContainer}>
              <TouchableOpacity onPress={pickImage}>
                <Image source={{ uri: profile.profilePicture }} style={styles.picture} />
              </TouchableOpacity>
              <TouchableOpacity onPress={deleteProfileImage} style={styles.deleteIcon}>
                <Avatar.Icon size={24} icon="close" color="white" style={{ backgroundColor: '#463458' }} />
              </TouchableOpacity>
            </View>
          ) : (
            <TouchableOpacity onPress={pickImage} >
              <Avatar.Icon size={120} icon="account" color="#A9A9A9" style={styles.avatar} />
            </TouchableOpacity>
          )}
        </View>
```

- Desktop OS: Windows 11
- Device: iphoine 14 Pro
- OS: iOS26
- RN version: 0.79.5
- RN architecture: new
- JS engine: Hermes
- Library version: 1.17.5

**Comment by manuthecoder** [comment]
confirmedf

**Comment by kirillzyusko** [comment]
https://github.com/user-attachments/assets/f7c95394-bed7-4b87-b485-ba8ac2d15d16

In example app it works... @asadarshad142 could you add a reproduction repo so that we would have the same codebase/environment?

**Comment by asadarshad142** [comment]
@kirillzyusko I faced issue with in my app where it was working before but than after updating to ios26, it stopped working.  Than for debugging i used same https://github.com/kirillzyusko/react-native-keyboard-controller/tree/main/example/src/screens/Examples/AwareScrollView example code, but didn't work. 
my version is "react-native-keyboard-controller": "1.17.5".

Did you tried on iOS 26 in your screen recording?

**Comment by kirillzyusko** [comment]
@asadarshad142 Yes, it was on iOS 26 (you can see the new keyboard UI which is specific to iOS 26).

Are you sure you re-compiled your app with 1.17.5 version? I. e. you re-installed pods, re-compiled app etc?

Can you send a video of how it works on your device?

**Comment by asadarshad142** [comment]
IOS

https://github.com/user-attachments/assets/cfbd72eb-8536-4e34-8177-c2b9ed8c80b4

Android

https://github.com/user-attachments/assets/faa56e99-dbd7-43cc-a41c-a3c3a9dd1bff

here are shots from ios and android. On android it works perfect. and yes i have re-compiled my app with 1.17.5 version. Also i use expo sdk53

**Comment by kirillzyusko** [comment]
@asadarshad142 you don't use XCode 26, right? You compile the app with XCode 16? Can you tell me exact version? Do you render `KeyboardAwareScrollView` inside the Modal?

Once you give the answer on my questions I'll try to reproduce the issue in example app!

**Comment by asadarshad142** [comment]
Iam using Xcode 16.2 to compile app. And i tried in Modal and without Modal, in both cases it dont work as intended.

**Comment by kirillzyusko** [comment]
Confirm, I can reproduce the problem! Looking into a root cause 👀 

(so far it seems XCode 16 + iOS 26 combination, because XCode 16 + iOS 18 was working well, XCode 26 + iOS 26 was working too)

**Comment by kirillzyusko** [comment]
Okay, it seems that problem happens because Appke broke their keyboard notification system. They dispatch `keyboardWillShow` and 16ms later dispatch `keyboardDidShow` and because of that everything is kind of broken 🤦‍♂️ 

I'll see what I can do here

**Comment by asadarshad142** [comment]
@kirillzyusko thanks alot . highly appreciate

**Comment by kirillzyusko** [comment]
@asadarshad142 which iOS beta version do you use? It seems like the video that I recorded was captured on iOS 26 beta 3, but on iOS 26 beta 4 it doesn't work (same as yours video).

**Comment by asadarshad142** [comment]
i have iOS26 beta 4. never managed to test on iOS beta 3

**Comment by petemusicpancake** [comment]
+1, same problem on IOS 26 beta 4
used to work fine on IOS 26 beta 3

**Comment by mbernabo** [comment]
+1 Same.

**Comment by kirillzyusko** [comment]
This problem is a very complex. Let me break down it into several problems:

1. `keyboardView` doesn't have animations on its `layer`. Basically it totally breaks the keyboard-controller and keyboard-controller doesn't emit `onMove` events (many components such as `KeyboardAwareScrollView`/`KeyboardAvoidingView` are heavily relying on this event). I'm currently trying to fix it in https://github.com/kirillzyusko/react-native-keyboard-controller/pull/1047 (have a partial success, onMove works for plain animations, but there is still certain problems, so I can not merge it as is).
2. `keyboardDidShow` is broken in iOS 26. Apple dispatches this event even when keyboard just starts its movement. I rely on the timing of this event, because I stop some expensive operations and run them only when keyboard is actually moving to save CPU resources. Now I stop them immediately when animation just starts, so again - I can not emit `onMove` event. (PR with potential fix https://github.com/kirillzyusko/react-native-keyboard-controller/pull/1062)
3. Theoretically I could add additional sync check inside `onEnd`, but because of the problem 2 I also get incorrect coordinates in `onEnd` handler 🤯 

So, to sum it up - problem 1 should be fixed on keyboard-controller level. Problem 2 - should be fixed on Apple side (I also can fix it on keyboard-controller side, but it's kind of ridiculous that I have to fix Apple bugs, PR is here: https://github.com/kirillzyusko/react-native-keyboard-controller/pull/1062)

<hr>

> [!WARNING]
> Please, don't spam with `+1` messages, it doesn't help at all. If you want to show that you have the same problem - react with emoji on the initial message.
>
> If you really want to speed up the time for fixing this problem, feel free to send a detailed feedback to Apple. Maybe if they see that the problem 2 affects many developers they will prioritize fixing 🤷‍♂️

**Comment by shahzebkhan-rw1** [comment]
@kirillzyusko maybe we should wait for final release of ios26 and it gets fixed by apple directly?

**Comment by kirillzyusko** [comment]
@shahzebkhan-rw1 definetely, but from my practice/observations - if Apple has bugs in beta version, most likely those bugs will be present in final version and they may not be fixed for months event after a stable release 😬

**Comment by kirillzyusko** [comment]
@asadarshad142 @shahzebkhan-rw1 @petemusicpancake it looks like the problem has been fixed in beta 5. Could you please confirm it?

**Comment by PatrickkZhao** [comment]
I can confirm this is fixed in beta 5.

In the previous beta 4, the response was inconsistent. A long press on the input field had a higher chance of scrolling it to the correct position.

Now, in beta 5, every click on the input field scrolls it to the correct position. The issue appears to be resolved.

**Comment by kirillzyusko** [comment]
I also published `1.18.3` that reflects all changes that were in `main` since `1.18.2`. If something still not working feel free to update the version and check again 🙌

**Comment by kirillzyusko** [comment]
It seems like the issue has been resolved. I'll close that issue, but if you discover, that something doesn't work again or doesn't work as expected - feel free to open a new issue with detailed information or post the comment here.

For me it seems like beta 5 is much more stable than beta 4, so let's close the issue 🤞

**Comment by jmeistrich** [comment]
Thanks a ton @kirillzyusko! In beta 5 it was firing onMove with progress 1 and then 0 when closing the keyboard, no animated progress. And updating from `1.18.0` to `1.18.3` fixed it. ❤️

**Comment by rajinsyed** [comment]
@kirillzyusko on ios 26 beta 6 the onMove stopped working again. no animated progress just jumps from 1 to 0.

**Comment by kirillzyusko** [comment]
@rajinsyed could you please share more info? I'm testing on `1.18.4`, iOS 26 beta 6, assembled with XCode 16.4 and XCode 26 beta 5. Here is my results:

https://github.com/user-attachments/assets/30ea1b3c-7635-46b7-a4b7-3d1948c4a966

https://github.com/user-attachments/assets/61b9e951-1cda-4665-9e59-947ce2f141e7

https://github.com/user-attachments/assets/b626ee96-3888-46fc-9906-4ac4e663083f

https://github.com/user-attachments/assets/0b940d51-cf98-452c-b852-7df377c535c9

**Comment by matthieugicquel** [comment]
The issue is still present in some cases 😔

Video from FabricExample, keyboard-controller from main today, iOS 26 beta 8.

In the video we see that the keyboard itself does not animate on close, it's not just the events/animations from keyboard-controller (as in the original repro).

https://github.com/user-attachments/assets/2bd98ea6-471a-4e5c-8c5a-341ef64f9c23

Interesting bit: on the Enabled/Disabled example, issue is present only when disabled.

https://github.com/user-attachments/assets/25ca92e6-9910-4f21-98bf-43a44be9be93

**Comment by matthieugicquel** [comment]
This non-animated keyboard is reproducible without rn-keyboard-controller, I've open an issue on React Native: https://github.com/facebook/react-native/issues/53626

**Comment by kirillzyusko** [comment]
Hi @matthieugicquel 

Sorry for a long response - was very busy last 3 weeks and literally didn't have a time to read and respond to messages. You are right, the keyboard gets hidden immediately when `resignFirstResponder` gets called (both `KeyboardController.dismiss()` and `Keyboard.dismiss()` from `react-native` calls `resignFirstResponder` internally). In iOS 26 (last betas) it seems like something is wrong and whenever you call `resignFirstResponder` keyboard gets dismissed immediately. I think it's iOS 26 bug and I hope it will be fixed before public release.

However, I found a use-case when immediate keyboard close ***potentially*** can be handy and may look even better than animated one: https://x.com/klemensstrasser/status/1955284572825853957?t=Rui36_sZCd3pEoKFc02N9w&s=35

I'll add a new option `animated` to `KeyboardController.dismiss` so that you can achieve the same transitions if needed and pass `KeyboardController.dismiss({ animated: false })` 👀

**Comment by erenkulaksiz** [comment]
Hello, had the same issue with Expo 52 + xcode 26.0.1 but upgrading to 1.19.1 fixed this issue. Thanks for the valuable information!!
